### ISSUE TITLE
008/great_prod.py

### ISSUE THREAD

**Issue by petr-tik** [zacharydenton/euler#1]
Do you have to cycle through all 13 digit long strings or can you split the input by 0? Why go through cpu cycles calculating the product that will be zero.

**Comment by zacharydenton** [comment]
In fact we can go further and split by both zero and one, and then skip any pieces of length < 13.

The problem is that this approach isn't necessarily faster in practice.

It's true that there's no point in calculating products including zero, but multiplying a few extra times within a contiguous string is going to be less overhead than splitting the string and then iterating through a bunch of noncontiguous strings. Multiplication is really fast on modern computers; memory access, less so.
