### ISSUE TITLE
Goal of this project: Languages or Problems?

### ISSUE THREAD

**Issue by gallettilance** [zacharydenton/euler#6]
Just curious what the grand vision for this project is - this is such an incredible repo! I would love to contribute some of my Project Euler code which is written in [ats-lang](http://www.ats-lang.org/) but I want to make sure this aligns with the maintainer's view.
Either way - happy to chat about it!

**Comment by zacharydenton** [comment]
Hey Lance, this is mainly just a repository collecting my personal solutions to PE problems, and a way for me to learn new languages (most recently Rust). I encourage you to post your ATS solutions in your own repository because I took a look at some of your other ATS code and it looks like 1) an ideal language for Project Euler and 2) you really know what you're doing with it!
